name: base-birches-scandinavia
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib=3.4
  - seaborn=0.11
  - numpy=1.21
  - pandas=1.3
  - pyyaml=5.4
  - pandas-plink=2.2.9
  - scikit-learn=0.24
  - scipy=1.7